# Generated by Django 4.2.7 on 2024-03-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0032_registropagosmodel_numero_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='numero_pago',
        ),
    ]
