# Generated by Django 4.2.7 on 2024-03-25 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0033_remove_registropagosmodel_numero_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='registropagosmodel',
            name='identificador',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='registropagosmodel',
            name='periodo_a_pagar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
