# Generated by Django 4.2.7 on 2024-04-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_registrocreditosmodel_identificador_unico'),
        ('calificaciones', '0035_identificadordepago'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificadorDePagoRegistroMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_a_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_restante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('periodo_a_pagar', models.IntegerField(blank=True, null=True)),
                ('fecha_oportuna', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.BooleanField(default=False)),
                ('simulador_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identificador_pago_manual', to='users.registrocreditosmodel')),
            ],
        ),
    ]
