# Generated by Django 4.2.7 on 2024-04-02 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_registrocreditosmodel_identificador_unico'),
        ('calificaciones', '0036_identificadordepagoregistroman'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPagosModelManual',
            fields=[
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='media/')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, null=True)),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo_a_pagar', models.IntegerField(blank=True, null=True)),
                ('simulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulador_unico', to='users.registrocreditosmodel')),
            ],
            options={
                'verbose_name': 'Registro pago usuario manual',
                'verbose_name_plural': 'Registro pago usuario manuales',
            },
        ),
    ]
