# Generated by Django 4.2.7 on 2024-04-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_registrocreditosmodel_identificador_unico'),
        ('calificaciones', '0037_registropagosmodelmanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagosmodelmanual',
            name='simulador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulador_unico_manual', to='users.registrocreditosmodel'),
        ),
    ]
